-- Add new columns to employee_profiles table for extended profile details
ALTER TABLE public.employee_profiles
ADD COLUMN IF NOT EXISTS role_code TEXT,
ADD COLUMN IF NOT EXISTS project_program TEXT,
ADD COLUMN IF NOT EXISTS position TEXT,
ADD COLUMN IF NOT EXISTS wes_mail TEXT,
ADD COLUMN IF NOT EXISTS wes_mail_pass TEXT,
ADD COLUMN IF NOT EXISTS house_number TEXT,
ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'India',
ADD COLUMN IF NOT EXISTS bank_account_name TEXT,
ADD COLUMN IF NOT EXISTS bank_city TEXT,
ADD COLUMN IF NOT EXISTS next_increment_date DATE,
ADD COLUMN IF NOT EXISTS race TEXT,
ADD COLUMN IF NOT EXISTS training_record TEXT,
ADD COLUMN IF NOT EXISTS education_worker_permit TEXT,
ADD COLUMN IF NOT EXISTS medical_health_condition TEXT,
ADD COLUMN IF NOT EXISTS has_driving_license BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS vehicle_information TEXT,
ADD COLUMN IF NOT EXISTS biometric_id TEXT,
ADD COLUMN IF NOT EXISTS samagra_id TEXT,
ADD COLUMN IF NOT EXISTS social_category TEXT,
ADD COLUMN IF NOT EXISTS degree TEXT,
ADD COLUMN IF NOT EXISTS professional_qualification_teaching TEXT,
ADD COLUMN IF NOT EXISTS employment_status TEXT DEFAULT 'Active',
ADD COLUMN IF NOT EXISTS engagement_type TEXT;